name: Get Stats

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '24 12 * * *'

jobs:
  get-stats:
    name: Get champion stats from Lolalytics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2

      - run: bun run main.ts

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add static/*
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
