name: Get Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  get-stats:
    name: Get champion stats from Lolalytics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
      
      - run: yarn
      - run: yarn ts-node main.ts